Homework 9 is done
mikutsky/Angular-HWs pull request #12
Opened 2019-11-05 12:27 UTC by mikutsky

По заданию все сделал:
Использовал редакс, храню выбранное изображение. Все манипуляции через стору.

От себя добавил таймер: если не выбирают изображение то показываю следущее, через 2,5 сек. Если выбранно последнее изображение в галлереи, то через 2,5сек заполняю галлерею новыми случайными изображениями и показываю первое во вьювере.
Также появились кнопки вперед и назад, для просмотра изображений галлереии по порядку.

Все манипуляции со стилями при наведении мыши, кликах сделал через Директы.

2019-11-05 12:36 UTC, mikutsky commented
Поправил работу таймера при выборе изображения.

2019-11-09 21:25 UTC, soulr1ver requested changes

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/redux/reducer.ts
> +}
вынеси логику с интервалом в сервис. здесь оставь просто объект, который будет хранить стейт галереи

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/redux/reducer.ts
> +export default function reducer(state = new State(), action: any) {
редьсюер не должен модифицировать старый объект. он должен возвращать новый

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/redux/reducer.ts
> +}
в общем, просто используй объект для этих целей

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/img.viewer/img.viewer.ts
> +      this.image = store.getState().gallery[store.getState().selectIndex];
вынеси это в переменную store.getState() и уже обращайся к ней за стейтом. так будет лучше, чем каждый раз вызывать данную функцию

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/img.viewer/img.viewer.ts
> +  public controlHandle(action: String) {
только string. с маленькой

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/directives/control.viewer.directive.ts
> +    this.stClick = "0.4";
в той директиве ты сделал правильно: задал дефолтное значение инпутам. тут можешь сделать аналогичное

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/directives/control.viewer.directive.ts
> +export class ControlViewerDirective implements OnInit {
внутри класса можешь использовать такой декоратор, как HostBinding. выглядеть он будет следующим образом:
@HostBinding('style.opacity')
  opacity: string;
где 'style.opacity' - это атрибут, к которому привязывается данная директива. теперь управлять этим атрибутом очень легко. всё, что тебе нужно, - это присвоить opacity новое значение

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/directives/control.viewer.directive.ts
> +    this._element.style.opacity = this.stHover;
поэтом тут будет this.opacity = this.stHover

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/directives/control.viewer.directive.ts
> +    this._element.style.opacity = this.default;
и т.д.

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/directives/hover.border.directive.ts
> +export class HoverBorderDirective implements OnInit {
аналогично

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/directives/hover.border.directive.ts
> +  constructor(element: ElementRef) {
этот элемент, кстати, можно приватным сделать

2019-11-09 21:25 UTC, soulr1ver commented on hw9/src/app/img.control/img.control.ts
> +  constructor() {}
если конструктор пустой - можешь его убирать

2019-11-18 21:32 UTC, soulr1ver approved these changes

2019-11-18 21:32 UTC, merged