Angular hw06
mikutsky/Angular-HWs pull request #8
Opened 2019-10-24 17:04 UTC by mikutsky

2019-10-24 23:18 UTC, soulr1ver requested changes
и конфликты. я тебе уже сказал, как поправить

2019-10-24 23:18 UTC, soulr1ver commented on hw6/src/app/img.viewer/img.viewer.ts
> +export class ImgViewer {
обязательно добавляй в названии класса то, что этот класс представляет, так будет проще понять в дальнейшем, что это. например, тут у тебя компонент - значит, имя должно быть: ImgViewerComponent. если директива ImgViewer Directive. и так далее

2019-10-24 23:18 UTC, soulr1ver commented on hw6/src/app/img.gallery/img.gallery.ts
> +      <img
выведи это циклом. всунь в тег имедж структурированную директиву *ngFor="let item of imageCollection", где item  - это твой текущий элемент на данной итерации

2019-10-24 23:18 UTC, soulr1ver commented on hw6/src/app/app.component.ts
> +export { AppComponent };
добавь экспорт просто перед классом. в данном месте это излишне

2019-10-25 07:00 UTC, mikutsky commented on hw6/src/app/img.viewer/img.viewer.ts
> +export class ImgViewer {
Понял Поправлю сейчас.

2019-10-25 07:03 UTC, mikutsky commented on hw6/src/app/img.gallery/img.gallery.ts
> +      <img
Понимал, что это можно сделать циклом. Натом занятии еще не проходили это. Я поправлю сейчас. Это полезно. Есть еще вопрос, по теме которую еще не проходили сейчас задам в телеграме

2019-10-25 07:04 UTC, mikutsky commented on hw6/src/app/app.component.ts
> +export { AppComponent };
Согласен =)

2019-11-03 02:15 UTC, soulr1ver approved these changes

2019-11-03 02:15 UTC, merged